# Generated by Django 6.0.2 on 2026-02-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('anno', models.PositiveIntegerField()),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_listino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.CharField(choices=[('disponibile', 'In Stock'), ('venduto', 'Venduto'), ('officina', 'In Preparazione')], default='disponibile', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_vendita_effettivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vendita', models.DateField()),
                ('venditore', models.CharField(max_length=100)),
                ('veicolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendita_effettuata', to='inventario.veicolo')),
            ],
        ),
    ]
