# Generated by Django 6.0.2 on 2026-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicolo',
            name='alimentazione',
            field=models.CharField(choices=[('benzina', 'Benzina'), ('diesel', 'Diesel'), ('gpl', 'GPL'), ('metano', 'Metano'), ('ibrida', 'Ibrida'), ('elettrica', 'Elettrica')], default='benzina', max_length=20),
        ),
        migrations.AddField(
            model_name='veicolo',
            name='cambio',
            field=models.CharField(choices=[('manuale', 'Manuale'), ('automatico', 'Automatico')], default='manuale', max_length=20),
        ),
        migrations.AddField(
            model_name='veicolo',
            name='classe_ambientale',
            field=models.CharField(choices=[('euro4', 'Euro 4'), ('euro5', 'Euro 5'), ('euro6', 'Euro 6'), ('elettrico', 'Elettrico/Zero')], default='euro6', max_length=20),
        ),
        migrations.AddField(
            model_name='veicolo',
            name='km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veicolo',
            name='n_proprietari',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
