# Generated by Django 6.0.2 on 2026-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_veicolo_alimentazione_veicolo_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veicolo',
            name='stato',
            field=models.CharField(choices=[('disponibile', 'In Stock'), ('venduto', 'Venduto'), ('officina', 'In Preparazione'), ('transito', 'In Transito')], default='disponibile', max_length=20),
        ),
    ]
